@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam responseMessageBelowArrow true

EmployeeManager -> IOManager : readInput()
IOManager --> EmployeeManager : List<String>

EmployeeManager -> CommandFactory : getCommandObjectList(List<String>)
CommandFactory --> EmployeeManager : List<Command> (ADD, MOD, SCH, DEL)

EmployeeManager -> Command : execute command (List<Command>)
activate Command

Command -> PersistentDAO : add/mod/del/sch(Employee)
PersistentDAO -> EmployeeTable : add/mod/del/sch(Employee)
EmployeeTable -> EmployeeTable : add/mod/del/sch collection
EmployeeTable --> PersistentDAO : Set<Employee>
PersistentDAO --> Command : Set<Employee>

EmployeeManager <-- Command : Set<Employee>
deactivate Command

EmployeeManager -> EmployeeManager : sort Set<Employee>

EmployeeManager -> IOManager : writeOutput(List<String>)
IOManager --> EmployeeManager : void
@enduml

@startuml
Command -> PersistentDAO : add/mod/del/sch(Employee)
PersistentDAO -> EmployeeTable : add/mod/del/sch(Employee)
EmployeeTable -> EmployeeTable : add/mod/del/sch collection
EmployeeTable --> PersistentDAO : Set<Employee>
PersistentDAO --> Command : void
@enduml

@startuml
DeleteCommand -> PersistentDAO : delete(Employee)
PersistentDAO -> EmployeeTable : delete(Employee)
EmployeeTable -> EmployeeTable : delete collection
EmployeeTable --> PersistentDAO : Set<Employee>
PersistentDAO --> DeleteCommand : void
@enduml

@startuml
ModifyCommand -> PersistentDAO : modify(Employee)
PersistentDAO -> EmployeeTable : modify(Employee)
EmployeeTable -> EmployeeTable : modify collection
EmployeeTable --> PersistentDAO : Set<Employee>
PersistentDAO --> ModifyCommand : void
@enduml

@startuml
SearchCommand -> PersistentDAO : search(Employee)
PersistentDAO -> EmployeeTable : search(Employee)
EmployeeTable -> EmployeeTable : search collection
EmployeeTable --> PersistentDAO : Set<Employee>
PersistentDAO --> SearchCommand : void
@enduml